# Generated by Django 2.1.2 on 2018-11-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_repair_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='admin',
        ),
    ]
